###############################################################################
#################################### commons #################################
###############################################################################
# 네임스페이스 생성
namespace:
  name: hivana
  annotations: {}
  labels: {
    istio-injection: enabled
  }

# host 부분에 도메인으로 등록할 주소 입력
istioGateway:
  servers:
    hosts:
      - "hivana.dev.sinsang.market"

# 자동 도메인 등록 (현재는 sandbox에서만 테스트 예정)
externalDns:
  domainFilter: "dev.sinsang.market"

# 서비스 이름 입력
fullnameOverride: hivana

# 서비스 포트 입력 (일반적으로 타겟포트도 동일하게 입력)
service:
  type: ClusterIP
  port: 5601
  targetPort: 5601

###############################################################################
############################### kibana values #################################
###############################################################################

cluster: hivana
version: 7.15.2
esRef: helastic
esServiceRef: helastic-coord-http
esNamespaceRef: helastic
