apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
- apiGroups: ["networking.istio.io"]
  resources: ["gateways", "virtualservices"]
  verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-{{ .Values.namespace.name }}
subjects:
- kind: ServiceAccount
  name: external-dns-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-{{ .Values.namespace.name }}
  template:
    metadata:
      namespace: {{ .Values.namespace.name }}
      labels:
        app: external-dns-{{ .Values.namespace.name }}
    spec:
      serviceAccountName: external-dns-{{ .Values.namespace.name }}
      containers:
      - name: external-dns-{{ .Values.namespace.name }}
        image: k8s.gcr.io/external-dns/external-dns:v0.7.6
        args:
        - --source=service
        - --source=ingress
        - --source=istio-gateway
        - --source=istio-virtualservice
        - --domain-filter={{ .Values.externalDns.domainFilter }} # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        - --provider=aws
        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
        - --registry=txt
        - --txt-owner-id=my-identifier
