---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ai-workload-istio-gateway
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http2-80
        protocol: HTTP2
      {{- with .Values.istioGateway.servers.hosts }}
      hosts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tls:
        httpsRedirect: true # sends 301 redirect for http requests
    - port:
        number: 443
        name: https-443
        protocol: HTTP
       {{- with .Values.istioGateway.servers.hosts }}
      hosts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
   
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  {{- with .Values.istioGateway.servers.hosts }}
  hosts:
    {{- toYaml . | nindent 2 }}
  {{- end }}

  gateways:
  - ai-workload-istio-gateway
  # - mesh # applies to all the sidecars in the mesh

  http:
  - match:
    - uri:
        prefix: /
      port: 443
    route:
    - destination:
        host: {{ .Values.fullnameOverride }}-kb-http
        port:
          number: {{ .Values.service.port }}
    timeout: 3600s