apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.cluster }}
  namespace: {{ .Values.namespace.name }}
spec:
  version: {{ .Values.version }}
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  elasticsearchRef:
    name: {{ .Values.esRef }}
    serviceName: {{ .Values.esServiceRef }}
    namespace: {{ .Values.esNamespaceRef }}
